#!/bin/sh

for command in apt su pkill ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	exa="exa -abghHliS" \
  duf="duf -all" \
  ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
  ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
  e="$EDITOR" \
  au="apt uninstall" \
  ar="apt reinstall" \
  ai="apt install" \
  aur="apt autoremove" \

# Misc.
alias \
	vim="nvim" \
