#!/bin/sh

for command in apt su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    ffmpeg="ffmpeg -hide_banner" \
    exa="exa -abghHliS" \
    duf="duf -all" \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    e="$EDITOR" \
    ar="apt remove" \
    are="apt reinstall" \
    ai="apt install" \
    aur="apt autoremove" \
    au="apt upgrade" \

# Misc.
alias \
    ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
    vim="nvim" \
